config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "links#new"
  resources :links, only: [:new, :create, :show, :index]
  get '/:slug', to: "redirects#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :slug, presence: true, uniqueness: true
  validates :url, presence: true
  validates :url, url: true
  has_many :redirect_events

  def generate_unique_slug
    unique = false

    until unique
      slug = 1.word
      if Link.where(slug: slug).none?
        unique = true
      end
    end

    self.slug = slug
  end
end

app/models/redirect_event.rb
class RedirectEvent < ApplicationRecord
  validates :link_id, presence: true
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.generate_unique_slug

    if @link.save
      redirect_to @link and return
    else
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def index
    @links = Link.all
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  def create
    @link = Link.find_by(slug: params[:slug])

    if @link.nil?
      flash[:message] = "Link not found"
      redirect_to root_path and return
    end

    @link.redirect_events.create
    
    redirect_to @link.url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RtrLinkr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">RTR Linkr</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Add New Link", new_link_path %></li>
          <li><%= link_to "View Link Analytics", links_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <body>
    <% if flash[:message] %>
      <div class="alert alert-warning">
        <%= flash[:message] %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/index.html.erb
<table class="table">
  <tr>
    <th>Redirect</th>
    <th>Original URL</th>
    <th>Count</th>
  </tr>
  <% @links.each do |link| %>
    <tr>
      <td><%= root_url + link.slug %></td>
      <td><%= link.url %></td>
      <td><%= link.redirect_events.count %></td>
    </tr>
  <% end %>
</table>

app/views/links/new.html.erb
<h1>Shorten a Link</h1>

<% if @link.errors.any? %>
  <ul>
    <% @link.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @link do |f| %>
  <%= f.label "ENTER URL" %>
  <%= f.url_field :url %>
  <%= f.submit %>
<% end %>

app/views/links/show.html.erb
<h3><%= root_url + @link.slug %> redirects to <%= @link.url %>
</h3>